### ISSUE TITLE
Validação de conteúdo do formulário

### ISSUE THREAD

**Issue by bmarques1234** [bmarques1234/CRUD#2]
Realizar uma validação do conteúdo do formulário no momento de realizar o request.
Conferir antes do request se o nome possue no mínimo 3 letras e os campos valor e estoque são realmente número. Após isso realizar o request, senão informar ao usuário o erro e continuar na tela atual.

**Comment by luantoni** [comment]
"campos valor e estoque são realmente número." tu já fez, não?
De resto, ok
